# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import onnxruntime
import face_analysis
import mask_renderer
import numpy
import numpy.linalg
import glob
import os.path
import model_zoo
import utils
import common
import cv2
import datetime
import albumentations
import albumentations.core.transforms_interface
import thirdparty
import data
import abc
import argparse
import model_download
import rec_add_mask_param
import zipfile
import numbers
import mxnet
import app
import data.rec_builder
import image
import pickle_object
import pathlib
import pickle
import arcface_onnx
import retinaface
import scrfd
import landmark
import attribute
import onnx
import time
import inswapper
import model_store
import cython
import distutils.core
import Cython.Build
import Cython.Distutils
import skimage
import math
import matplotlib.pyplot
import mpl_toolkits.mplot3d
import morphabel_model
import scipy.io
import storage
import filesystem
import constant
import hashlib
import requests
import tqdm
import errno
import pip
import pip._internal
import nvidia.dali
import download

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

